config/routes.rb
Rails.application.routes.draw do
  root to: 'feed_posts#index'

  devise_for :users
  resources :users, only: [:show]
  resources :follows, only: [:create, :destroy]

  resources :feed_posts, only: [:index] do
    resources :comments, only: [:create]
  end

  resources :posts, only: [:new, :create, :show] do
    resources :comments, only: [:create]
  end
  resources :likes, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  has_many :likes, as: :likeable, dependent: :destroy

  validates :content, presence: true, length: { minimum: 2, maximum: 1000 }
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :following, class_name: 'User'
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :likeable, polymorphic: true

  validates :user_id, uniqueness: { scope: %i[likeable_id likeable_type] }
end

app/models/post.rb
class Post < ApplicationRecord
  include ImageUploader::Attachment(:image)

  belongs_to :user

  has_many :comments, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy

  validates :image_data, presence: true
  validates :description, presence: true, length: { maximum: 2200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_many :follower_follows, foreign_key: :following_id, class_name: 'Follow', dependent: :destroy
  has_many :followers, through: :follower_follows, source: :follower

  has_many :following_follows, foreign_key: :follower_id, class_name: 'Follow', dependent: :destroy
  has_many :followings, through: :following_follows, source: :following

  validates :nickname, presence: true, uniqueness: { case_sensitive: false }
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates :name, length: { maximum: 50 }
  validates :bio, length: { maximum: 300 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authorization
  include Pagy::Backend

  protect_from_forgery with: :exception, prepend: true
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[username name bio])
  end

  def after_sign_in_path_for(_source)
    feed_posts_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post

  def create
    @comment = @post.comments.create(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.json do
          render json: { entries: render_to_string(partial: 'comment', formats: [:html],
                                                   locals: { comment: @comment }) }
        end
      end
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/concerns/authorization.rb
module Authorization
  extend ActiveSupport::Concern

  included do
    include Pundit::Authorization

    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

    private

    def user_not_authorized
      flash[:danger] = t 'global.flash.not_authorized'
      redirect_to(request.referer || root_path)
    end
  end
end

app/controllers/feed_posts_controller.rb
class FeedPostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @pagy, @posts = pagy Post.where(user_id: current_user.id)
                             .or(Post.where(user_id: current_user.followings.pluck(:id)))
                             .includes(:user, :likes)
                             .order(created_at: :desc)
    @pagy_metadata = pagy_metadata(@pagy)

    respond_to do |format|
      format.html
      format.json do
        render json: { entries: render_to_string(partial: 'posts', formats: [:html]),
                       pagy: pagy_metadata(@pagy) }
      end
    end
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :authenticate_user!

  def create
    follower_user = current_user
    following_user = User.find(params[:followed_id])

    follow = Follow.new(follower: follower_user, following: following_user)

    respond_to do |format|
      if follow.save
        format.json do
          render json: { entries: render_to_string(partial: 'unfollow_button', formats: [:html],
                                                   locals: { follow: follow }) }
        end
      end
    end
  end

  def destroy
    follow = Follow.find(params[:id])
    following_user = follow.following

    respond_to do |format|
      if follow.destroy
        format.json do
          render json: { entries: render_to_string(partial: 'follow_button', formats: [:html],
                                                   locals: { user: following_user }) }
        end
      end
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    @like = current_user.likes.new(like_params)

    respond_to do |format|
      if @like.save
        format.json do
          render json: { entries: render_to_string(partial: 'dislike_button', formats: [:html],
                                                   locals: { like: @like }) }
        end
      end
    end
  end

  def destroy
    @like = current_user.likes.find(params[:id])
    @likeable = @like.likeable

    respond_to do |format|
      if @like.destroy
        format.json do
          render json: { entries: render_to_string(partial: 'like_button', formats: [:html],
                                                   locals: { likeable: @likeable }) }
        end
      end
    end
  end

  private

  def like_params
    params.require(:like).permit(:likeable_id, :likeable_type)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: %i[show]
  before_action :authorize_post!
  after_action :verify_authorized

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    if @post.save
      redirect_to feed_posts_path, flash: { success: 'Post was created successfully!' }
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  private

  def post_params
    params.require(:post).permit(:image, :description)
  end

  def authorize_post!
    authorize(@post || Post)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user

  def show
    @posts = @user.posts
  end

  def followers
    @followers = @user.followers
  end

  def followings
    @followings = @user.followings
  end

  private

  def load_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def is_current_user?(user)
    current_user.present? && current_user == user
  end
end

app/views/comments/_comment.html.erb
<li data-controller="counter"
    data-counter-score-value="<%= comment.likes.count %>"
    class="flex justify-between">
  <div class="flex flex-col mb-5">
    <p class="mb-2">
      <%= link_to comment.user.nickname, user_path(comment.user), class: "font-bold" %>
      <%= render partial: 'shared/truncator', locals: { content: comment.content, length: 110} %>
    </p>

    <div class="flex flex-row items-center gap-4">
      <div>
        <p class="uppercase text-xs text-gray-400"><%= time_ago_in_words(comment.created_at) %> ago</p>
      </div>
      <div>
        <label for="likeable-<%= comment.id %>" class="text-xs font-bold text-gray-400 cursor-pointer"><span data-counter-target="score"></span> likes</label>
        <%= render partial: 'likes/likeable_list', locals: { likeable: comment }  %>
      </div>
    </div>
  </div>
  <%= render partial: 'likes/likeable', locals: { likeable: comment } %>
</li>

app/views/comments/_form.html.erb
<div class="flex">
  <textarea data-action="comment#active"
            data-comment-target="content"
            class="textarea textarea-bordered w-full resize-none h-0"
            placeholder="Add a comment..."
            id="comment-btn"></textarea>
  <button data-action="comment#post"
          data-comment-target="button"
          class="btn ml-2">
    Post
  </button>
</div>

app/views/feed_posts/_posts.html.erb
<% @posts.each do |post| %>
  <li class="card md:w-3/4 lg:w-1/2 max-w-fit bg-base-100 md:shadow-xl mb-16 mx-auto">
    <div class="card-body p-3 pl-8">
      <h2 class="font-bold"><%= link_to post.user.nickname, user_path(post.user) %></h2>

    </div>
    <figure class="bg-base-300 min-w-[50%] max-w-full">
      <%= image_tag post.image_url(:square) %>
    </figure>
    <div data-controller="counter"
         data-counter-score-value="<%= post.likes.count %>"
         class="card-body pt-4">
      <div class="flex flex-row gap-2">
        <%= render partial: 'likes/likeable', locals: { likeable: post } %>
        <label for="comment-btn" class="btn btn-sm btn-square btn-ghost">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24"><path d="M20.656 17.008a9.993 9.993 0 10-3.59 3.615L22 22z" fill="none" stroke="currentColor" stroke-linejoin="round" stroke-width="2"></path></svg>
        </label>
      </div>
      <div>
        <label for="likeable-<%= post.id %>" class="text-sm font-bold mb-1 cursor-pointer"><span data-counter-target="score"></span> likes</label>
        <%= render partial: 'likes/likeable_list', locals: { likeable: post }  %>
      </div>
      <p>
        <span class="link link-hover font-bold"><%= link_to post.user.nickname, user_path(post.user) %></span>
        <%= render partial: 'shared/truncator', locals: { content: post.description, length: 110 } %>
      </p>
      <div data-controller="comment"
           data-comment-disabled-class="btn-disabled"
           data-comment-url-value="<%= post_comments_path(post) %>">
        <ul data-comment-target="comments">
        </ul>
        <p class="link link-hover text-sm text-gray-400 mb-2"><%= link_to "View all comments", post_path(post) %></p>
        <p class="uppercase text-xs text-gray-400 mb-2"><%= time_ago_in_words(post.created_at) %> ago</p>
        <%= render "comments/form" %>
      </div>
    </div>
  </li>
<% end %>

app/views/feed_posts/index.html.erb
<div class="min-h-screen py-10 bg-base-200">
  <div data-controller="infinite-scroll"
       data-action="scroll@window->infinite-scroll#scroll"
       data-infinite-scroll-url-value="<%= @pagy_metadata[:next_url] %>">
    <ul data-infinite-scroll-target="entries">
      <%= render partial: 'posts', class: "flex" %>
    </ul>
  </div>
</div>

app/views/follows/_follow.html.erb
<div data-controller="counter"
     data-counter-score-value="<%= user.followers.count %>"
     class="my-8">
  <div class="flex flex-col text-center">
    <div class="flex justify-between items-center mb-4">
      <p><span class="font-bold"><%= user.posts.count %></span> posts</p>
      <label for="followings" class="cursor-pointer"><span data-counter-target="score" class="font-bold"></span> followers</label>
      <label for="followers" class="cursor-pointer"><span class="font-bold"><%= user.followings.count %></span> following</label>
    </div>

    <% unless is_current_user?(user) %>
      <% follow = current_user.following_follows.find_by(following_id: user.id) %>
      <% if follow.nil? %>
        <%= render partial: 'follows/follow_button', locals: { user: user } %>
      <% else %>
        <%= render partial: 'follows/unfollow_button', locals: { follow: follow } %>
      <% end %>
    <% end %>
  </div>

  <input type="checkbox" id="followings" class="modal-toggle">
  <label for="followings" class="modal cursor-pointer">
    <label class="modal-box relative p-0" for="">
      <ul class="flex flex-col divide-y divide-solid divide-slate-400/25">
        <li class="p-5">
          <p class="text-center font-bold text-2xl">Followings</p>
        </li>
        <% if user.followings.blank? %>
          <li class="p-5">
            <p>You don't follow anyone yet...</p>
          </li>
        <% else %>
          <% user.followings.each do |user| %>
            <li class="p-5">
              <p class="font-bold"><%= user.nickname %></p>
              <small><%= user.name %></small>
            </li>
          <% end %>
        <% end %>
      </ul>
    </label>
  </label>

  <input type="checkbox" id="followers" class="modal-toggle">
  <label for="followers" class="modal cursor-pointer">
    <label class="modal-box relative p-0" for="">
      <ul class="flex flex-col divide-y divide-solid divide-slate-400/25">
        <li class="p-5">
          <p class="text-center font-bold text-2xl">Followers</p>
        </li>
        <% if user.followers.blank? %>
          <li class="p-5">
            <p>You don't have any subscribers yet...</p>
          </li>
        <% else %>
          <% user.followers.each do |user| %>
            <li class="p-5">
              <p class="font-bold"><%= user.nickname %></p>
              <small><%= user.name %></small>
            </li>
          <% end %>
        <% end %>
      </ul>
    </label>
  </label>
</div>

app/views/follows/_follow_button.html.erb
<div data-controller="switcher"
     data-switcher-target="switcher"
     data-switcher-url-value="<%= follows_path %>"
     data-switcher-params-value="<%= { followed_id: user.id }.to_param %>">
  <button data-action="switcher#on counter#add"
          class="btn btn-xs btn-primary btn-wide">
    Follow
  </button>
</div>

app/views/follows/_unfollow_button.html.erb
<div data-controller="switcher"
     data-switcher-target="switcher"
     data-switcher-url-value="<%= follow_path(follow) %>">
  <button data-action="switcher#off counter#subtract"
          class="btn btn-xs btn-primary btn-outline btn-wide">
    Unfollow
  </button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-theme="light">
  <head>
    <title>CdgCoursework</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'static_pages/navbar/navbar' %>
    <%= yield %>
    <%= render 'static_pages/footer' %>


  </body>
</html>

app/views/likes/_dislike_button.html.erb
<% if like.likeable.class == Comment %>
  <% options = { btn_class: "btn btn-xs btn-square btn-ghost", icon_class: "h-3 w-3" } %>
<% else %>
  <% options = { btn_class: "btn btn-sm btn-square btn-ghost", icon_class: "h-6 w-6" } %>
<% end %>

<div data-controller="switcher"
     data-switcher-target="switcher"
     data-switcher-url-value="<%= like_path(like) %>">
  <button data-action="switcher#off counter#subtract"
          class="<%= options[:btn_class] %>">
    <svg xmlns="http://www.w3.org/2000/svg" class="<%= options[:icon_class] %>" fill="#ed4956" viewBox="0 0 48 48"><path d="M34.6 3.1c-4.5 0-7.9 1.8-10.6 5.6-2.7-3.7-6.1-5.5-10.6-5.5C6 3.1 0 9.6 0 17.6c0 7.3 5.4 12 10.6 16.5.6.5 1.3 1.1 1.9 1.7l2.3 2c4.4 3.9 6.6 5.9 7.6 6.5.5.3 1.1.5 1.6.5s1.1-.2 1.6-.5c1-.6 2.8-2.2 7.8-6.8l2-1.8c.7-.6 1.3-1.2 2-1.7C42.7 29.6 48 25 48 17.6c0-8-6-14.5-13.4-14.5z"></path></svg>
  </button>
</div>

app/views/likes/_like_button.html.erb
<% if likeable.class == Comment %>
<% options = { btn_class: "btn btn-xs btn-square btn-ghost", icon_class: "h-3 w-3" } %>
<% else %>
<% options = { btn_class: "btn btn-sm btn-square btn-ghost", icon_class: "h-6 w-6" } %>
<% end %>

<div data-controller="switcher"
     data-switcher-target="switcher"
     data-switcher-url-value="<%= likes_path %>"
     data-switcher-params-value="<%= { likeable_id: likeable.id, likeable_type: likeable.class }.to_param('like') %>">
  <button data-action="switcher#on counter#add"
          class="<%= options[:btn_class] %>">
    <svg xmlns="http://www.w3.org/2000/svg" class="<%= options[:icon_class] %>" fill="currentColor" viewBox="0 0 24 24"><path d="M16.792 3.904A4.989 4.989 0 0121.5 9.122c0 3.072-2.652 4.959-5.197 7.222-2.512 2.243-3.865 3.469-4.303 3.752-.477-.309-2.143-1.823-4.303-3.752C5.141 14.072 2.5 12.167 2.5 9.122a4.989 4.989 0 014.708-5.218 4.21 4.21 0 013.675 1.941c.84 1.175.98 1.763 1.12 1.763s.278-.588 1.11-1.766a4.17 4.17 0 013.679-1.938m0-2a6.04 6.04 0 00-4.797 2.127 6.052 6.052 0 00-4.787-2.127A6.985 6.985 0 00.5 9.122c0 3.61 2.55 5.827 5.015 7.97.283.246.569.494.853.747l1.027.918a44.998 44.998 0 003.518 3.018 2 2 0 002.174 0 45.263 45.263 0 003.626-3.115l.922-.824c.293-.26.59-.519.885-.774 2.334-2.025 4.98-4.32 4.98-7.94a6.985 6.985 0 00-6.708-7.218z"></path></svg>
  </button>
</div>

app/views/likes/_likeable.html.erb
<% like = current_user.likes.find_by(likeable: likeable) %>
<% if like.nil? %>
<%= render partial: 'likes/like_button', locals: { likeable: likeable } %>
<% else %>
<%= render partial: 'likes/dislike_button', locals: { like: like } %>
<% end %>

app/views/likes/_likeable_list.html.erb
<input type="checkbox" id="likeable-<%= likeable.id %>" class="modal-toggle">
<label for="likeable-<%= likeable.id %>" class="modal cursor-pointer">
  <label class="modal-box relative p-0" for="">
    <ul class="flex flex-col divide-y divide-solid divide-slate-400/25">
      <li class="p-5">
        <p class="text-center font-bold text-2xl">Likes</p>
      </li>
      <% if likeable.likes.blank? %>
        <li class="p-5">
          <p>Nobody liked it yet...</p>
        </li>
      <% else %>
      <% likeable.likes.each do |like| %>
        <li class="p-5">
          <p class="font-bold"><%= like.user.nickname %></p>
          <small><%= like.user.name %></small>
        </li>
      <% end %>
      <% end %>
    </ul>
  </label>
</label>

app/views/posts/_form.html.erb
<%= form_with model: post, class: "card flex-shrink-0 w-full max-w-fit shadow-2xl bg-base-100 mx-auto" do |f| %>
  <div class="card-body">
    <div class="flex flex-col">
      <div class="lg:mx-10 text-center">
        <div class='form-control mb-5'>
          <%= f.hidden_field :image, value: post.cached_image_data, id: nil %>
          <%= f.file_field :image %>
        </div>

        <div class='form-control mb-10'>
          <div class="label">
            <%= f.label :description, class: "label-text" %>
          </div>
          <%= f.text_area :description, placeholder: :description, class: "textarea textarea-bordered" %>
        </div>

        <%= f.submit "Загрузить", class: 'btn btn-wide btn-primary' %>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/new.html.erb
<div class="flex flex-col min-h-screen py-10 md:px-12 bg-base-200">
  <div class="prose text-3xl mb-5 mx-auto">
    <h2 class="text-base-content">New post</h2>
  </div>

  <%= render 'form', post: @post %>
</div>

app/views/posts/show.html.erb
<div class="min-h-fit py-10 md:px-12 bg-base-200">
  <div class="card lg:card-side max-w-fit bg-base-100 md:shadow-xl mx-auto">
    <div class="lg:hidden card-body p-3 pl-8">
      <h2 class="font-bold"><%= link_to @post.user.nickname, user_path(@post.user) %></h2>
    </div>

    <figure class="bg-base-300 min-w-[50%] max-w-full">
      <%= image_tag @post.image_url(:square) %>
    </figure>

    <div data-controller="comment"
         data-comment-disabled-class="btn-disabled"
         data-comment-url-value="<%= post_comments_path(@post) %>"
         class="card-body min-w-[50%] lg:max-w-2xl flex flex-col justify-between divide-y divide-solid divide-slate-400/25 p-0">
      <div class="hidden lg:block px-10 pt-5 pb-3">
        <h2 class="font-bold"><%= link_to @post.user.nickname, user_path(@post.user) %></h2>
      </div>

      <div class="flex-grow p-10 py-5 overflow-auto h-48">
        <div class="mb-5">
          <p class="mb-2">
            <span class="font-bold"><%= link_to @post.user.nickname, user_path(@post.user) %></span>
            <%= @post.description %>
          </p>
          <p class="uppercase text-xs text-gray-400"><%= time_ago_in_words(@post.created_at) %> ago</p>
        </div>
        <ul data-comment-target="comments">
          <%= render @post.comments  %>
        </ul>
      </div>

      <div data-controller="counter"
           data-counter-score-value="<%= @post.likes.count %>"
           class="p-10 py-5">
        <div class="flex flex-row gap-2 mb-2">
          <%= render partial: 'likes/likeable', locals: { likeable: @post } %>
          <label for="comment-btn" class="btn btn-sm btn-square btn-ghost">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24"><path d="M20.656 17.008a9.993 9.993 0 10-3.59 3.615L22 22z" fill="none" stroke="currentColor" stroke-linejoin="round" stroke-width="2"></path></svg>
          </label>
        </div>
        <div>
          <label for="likeable-<%= @post.id %>" class="text-sm font-bold mb-1 cursor-pointer"><span data-counter-target="score"></span> likes</label>
          <%= render partial: 'likes/likeable_list', locals: { likeable: @post }  %>
        </div>
        <p class="uppercase text-xs text-gray-400 mb-4"><%= time_ago_in_words(@post.created_at) %> ago</p>
        <%= render "comments/form" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_truncator.html.erb
<span data-controller="truncator"
     data-truncator-length-value="<%= length %>">
    <span data-truncator-target="content">
      <%= content %>
    </span>
    <button data-action="truncator#view"
            data-truncator-target="button"
            class="link text-gray-400">
      more
    </button>
</span>

app/views/static_pages/_footer.html.erb
<footer class="footer footer-center p-10 bg-base-200 text-base-content rounded">
  <div>
    <p>Copyright © 2022 - All right reserved by ACME Industries Ltd</p>
  </div>
</footer>

app/views/static_pages/navbar/_user.html.erb
<div class="navbar-center hidden sm:block">
  <div class="form-control">
    <input type="text" placeholder="Search" class="input input-bordered">
  </div>
</div>

<div class="navbar-end gap-2">
  <a href="<%= root_path %>" class="btn btn-square btn-ghost">
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="inline-block w-6 h-6 stroke-current"><path d="M9.005 16.545a2.997 2.997 0 012.997-2.997h0A2.997 2.997 0 0115 16.545V22h7V11.543L12 2 2 11.543V22h7.005z" fill="none" stroke="currentColor" stroke-linejoin="round" stroke-width="2"></path></svg>
  </a>
  <a href="<%= new_post_path %>" for="create-post" class="btn modal-button btn-square btn-ghost">
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="inline-block w-6 h-6 stroke-current"><path d="M2 12v3.45c0 2.849.698 4.005 1.606 4.944.94.909 2.098 1.608 4.946 1.608h6.896c2.848 0 4.006-.7 4.946-1.608C21.302 19.455 22 18.3 22 15.45V8.552c0-2.849-.698-4.006-1.606-4.945C19.454 2.7 18.296 2 15.448 2H8.552c-2.848 0-4.006.699-4.946 1.607C2.698 4.547 2 5.703 2 8.552z" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path><line fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" x1="6.545" x2="17.455" y1="12.001" y2="12.001"></line><line fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" x1="12.003" x2="12.003" y1="6.545" y2="17.455"></line></svg>
  </a>

  <%= render 'static_pages/theme_changer' %>

  <div class="dropdown dropdown-end">
    <label tabindex="0" class="btn btn-ghost btn-circle avatar">
      <div class="w-10 rounded-full">
        <img src="https://api.lorem.space/image/face?hash=33791">
      </div>
    </label>
    <ul tabindex="0" class="mt-3 p-2 shadow menu menu-compact dropdown-content bg-base-100 rounded-box w-52">
      <li><%= link_to "Profile", user_path(current_user) %></li>
      <li><%= link_to "Settings", edit_user_registration_path %></li>
      <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
    </ul>
  </div>
</div>

app/views/users/show.html.erb
<div class="flex flex-col min-h-screen py-10 bg-base-200 divide-y divide-solid divide-slate-400/25">
  <div class="flex flex-col mx-auto min-w-[25%] max-w-[35%]">
    <p class="text-4xl"><%= @user.nickname %></p>
    <p class="font-bold"><%= @user.name %></p>
    <%= render 'follows/follow', user: @user %>
    <p><%= @user.bio %></p>
  </div>

  <div class="mb-10 pt-6 mx-auto">
    <ul class="grid grid-cols-3 gap-1">
      <% @posts.each do |post| %>
        <li class="transform z-0 hover:z-10 transition duration-500 hover:scale-105">
          <a href="<%= post_path(post) %>" >
            <%= image_tag post.image_url(:preview) %>
          </a>
        </li>
      <% end %>
    </ul>
  </div>
</div>